name: Deploy to InfinityFree
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: htdocs/
          # This helps if InfinityFree's firewall is being picky
          protocol: ftp
          port: 21
          
